-- https://wiki.hyprland.org/Configuring/Variables/#decoration

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        inactive_opacity = 0.7,
        blur = {
            enabled = true,
            size = 3,
            passes = 3,
            new_optimizations = true,
            ignore_opacity = false,
            xray = true,
        },
        dim_special = 0.3,
    },
})

hl.on("config.reloaded", function()
    hl.exec_cmd("gsettings set org.gnome.desktop.interface icon-theme 'Catppuccin-Mocha'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Catppuccin-Mocha-BL-LB'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme 'oomox-Catppuccin-Mocha'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface font-name 'DejaVuSansMono Nerd Font 10'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface document-font-name 'DejaVuSansMono Nerd Font 10'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface monospace-font-name 'DejaVuSansMono Nerd Font 9'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface font-hinting 'full'")
end)

