group {
  col.border_active = $sapphire
  col.border_inactive = $rosewater

  groupbar {
    render_titles = true
    height = 30
    font_size = 12
    font_family = "AnonymicePro Nerd Font"
    text_color = $crust
    col.active = $peach
    col.inactive = $lavender
    stacked = false
  }
}
