-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    group = {
        col = {
            border_active = { colors = { "rgba(ca9ee6ff)", "rgba(f2d5cfff)" }, angle = 45 },
            border_inactive = { colors = { "rgba(b4befecc)", "rgba(6c7086cc)" }, angle = 45 },
            border_locked_active = { colors = { "rgba(ca9ee6ff)", "rgba(f2d5cfff)" }, angle = 45 },
            border_locked_inactive = { colors = { "rgba(b4befecc)", "rgba(6c7086cc)" }, angle = 45 },
        },
        groupbar = {
            enabled = true,
            gradients = true,
            render_titles = true,
            height = 30,
            font_size = 14,
            font_family = "\"DejaVuSansMono Nerd Font\"",
            stacked = false,
        },
    },
})

