-- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- workspace = w[tv1], gapsout:0, gapsin:0
-- workspace = f[1], gapsout:0, gapsin:0
-- windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
-- windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
-- windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
-- windowrulev2 = rounding 0, floating:0, onworkspace:f[1]
--
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.workspace_rule({
    workspace = workspace_terminals,
    monitor = output_top,
})

hl.workspace_rule({
    workspace = workspace_notes,
    monitor = output_right,
})

hl.workspace_rule({
    workspace = workspace_browser,
    monitor = output_left,
})

hl.workspace_rule({
    workspace = workspace_communications,
    monitor = output_left,
})

hl.workspace_rule({
    workspace = workspace_learning,
    monitor = output_right,
})

hl.workspace_rule({
    workspace = workspace_email,
    monitor = output_right,
})

hl.workspace_rule({
    workspace = workspace_reading,
    monitor = output_right,
})

hl.workspace_rule({
    workspace = workspace_file_browser,
    monitor = output_top,
})

hl.workspace_rule({
    workspace = workspace_remote,
    monitor = output_top,
})

hl.workspace_rule({
    workspace = workspace_top,
    monitor = output_right,
})

