-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.on("hyprland.start", function()
    hl.exec_cmd(terminal)
    hl.exec_cmd(fileManager)
    hl.exec_cmd(browser)
    hl.exec_cmd(btop)
    hl.exec_cmd("obsidian")
    hl.exec_cmd(neomutt)
    hl.exec_cmd(remote)
    hl.exec_cmd("1password")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("awww-daemon --format xrgb")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("/usr/bin/lxqt-policykit-agent &")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user import-environment DISPLAY WAYLAND_DISPLAY DBUS_SESSION_BUS_ADDRESS")
end)

