-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.bind("SHIFT+" .. mainMod .. " + R", hl.dsp.exec_cmd("hyprctl reload; killall ags ydotool; ags &"), { release = true })

-- See https://wiki.hyprland.org/Configuring/Keywords/
hl.bind(mainMod .. " + g", hl.dsp.group.toggle())

-- Toggle between tabbed and stacked layout
hl.bind(mainMod .. " + ALT + k", hl.dsp.group.next())
hl.bind(mainMod .. " + ALT + j", hl.dsp.group.prev())

-- Move window with mainMod + motion keys
hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.move({ into_or_create_group = "l" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.move({ into_or_create_group = "r" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.move({ into_or_create_group = "u" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.move({ into_or_create_group = "d" }))

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu))

hl.bind(mainMod .. " + ALT + l", hl.dsp.exec_cmd("hyprlock"))

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SHIFT + q", hl.dsp.window.close())
hl.bind(mainMod .. " + b", hl.dsp.exec_cmd("brave"))
hl.bind(mainMod .. " + o", hl.dsp.exec_cmd("obsidian"))
hl.bind(mainMod .. " + t", hl.dsp.exec_cmd(btop))
hl.bind(mainMod .. " + m", hl.dsp.exec_cmd(neomutt))
hl.bind(mainMod .. " + n", hl.dsp.exec_cmd(news_reader))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- Fullscreen
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))

-- Floating
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.float({ action = "toggle" }))

-- Screenshot, Record, OCR, Color picker, Clipboard history
hl.bind("SUPER + V", hl.dsp.exec_cmd("pkill fuzzel || cliphist list | fuzzel  --match-mode fzf --dmenu | cliphist decode | wl-copy"))
hl.bind("SUPER + Period", hl.dsp.exec_cmd("pkill fuzzel || ~/.local/bin/fuzzel-emoji"))
hl.bind("CTRL+SHIFT+ALT + Delete", hl.dsp.exec_cmd("pkill wlogout || wlogout -p layer-shell"))

-- OCR
hl.bind("SUPER+SHIFT + T", hl.dsp.exec_cmd("grim -g \"$(slurp $SLURP_ARGS)\" \"tmp.png\" && tesseract -l eng \"tmp.png\" - | wl-copy && rm \"tmp.png\""))
hl.bind("CTRL+SUPER+SHIFT + S", hl.dsp.exec_cmd("grim -g \"$(slurp $SLURP_ARGS)\" \"tmp.png\" && tesseract \"tmp.png\" - | wl-copy && rm \"tmp.png\""))

-- Color picker
hl.bind("SUPER+SHIFT + C", hl.dsp.exec_cmd("hyprpicker -a"))

-- Fullscreen screenshot
hl.bind("Print", hl.dsp.exec_cmd("mkdir -p ~/Pictures/Screenshots && ~/.local/bin/grimblast.sh --notify copysave active ~/Pictures/Screenshots/Screenshot_\"$(date '+%Y-%m-%d_%H.%M.%S')\".png"), { locked = true })
hl.bind("CTRL + Print", hl.dsp.exec_cmd("mkdir -p ~/Pictures/Screenshots && ~/.local/bin/grimblast.sh --notify copysave screen ~/Pictures/Screenshots/Screenshot_\"$(date '+%Y-%m-%d_%H.%M.%S')\".png"), { locked = true })
hl.bind("CTRL+SHIFT + Print", hl.dsp.exec_cmd("mkdir -p ~/Pictures/Screenshots && ~/.local/bin/grimblast.sh --notify copysave area ~/Pictures/Screenshots/Screenshot_\"$(date '+%Y-%m-%d_%H.%M.%S')\".png"), { locked = true })

-- Recording stuff
hl.bind("SUPER+ALT + R", hl.dsp.exec_cmd("~/.local/bin/record-script.sh"))
hl.bind("CTRL+ALT + R", hl.dsp.exec_cmd("~/.local/bin/record-script.sh --fullscreen"))
hl.bind("SUPER+SHIFT+ALT + R", hl.dsp.exec_cmd("~/.local/bin/record-script.sh --fullscreen-sound"))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- 1password
hl.bind("CONTROL+SHIFT + Space", hl.dsp.exec_cmd("1password"))

-- Garuda Update
hl.bind(mainMod .. "+ALT + U", hl.dsp.exec_cmd("ghostty --class='com.waybar.garuda' -e zsh -c 'garuda-update && (read -p \\\"Update complete. Press Enter to exit.\\\" && exit 0) || (read -p \\\"Update failed. Press Enter to exit.\\\" && exit 1)'"))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
