-- Example per-device config
-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

