-- See https://wiki.hyprland.org/Configuring/Environment-variables/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "default")
hl.env("GDK_SCALE", "1")
hl.env("BROWSER", "firefox.desktop")

-- Set electron to use wayland
hl.env("ELECTRON_USE_OZONE", "1")
hl.env("OZONE_PLATFORM", "wayland brave --enable-features=UseOzonePlatform")

-- Set wayland as GDK backend
hl.env("GDK_BACKEND", "wayland")

