-- https://wiki.hyprland.org/Configuring/Variables/#gestures
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})
