-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/variables.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("variables")

-- Source: ~/.config/hypr/binding.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("binding")
-- Source: ~/.config/hypr/monitor.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("monitor")

-- Source: ~/.config/hypr/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("autostart")

-- Source: ~/.config/hypr/appearance/general.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("appearance.general")
-- Source: ~/.config/hypr/appearance/decoration.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("appearance.decoration")
-- Source: ~/.config/hypr/appearance/animations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("appearance.animations")
-- Source: ~/.config/hypr/appearance/workspaces.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("appearance.workspaces")
-- Source: ~/.config/hypr/appearance/group.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("appearance.group")

-- Source: ~/.config/hypr/env.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("env")

-- Source: ~/.config/hypr/dwindle.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("dwindle")
-- Source: ~/.config/hypr/misc.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("misc")
-- Source: ~/.config/hypr/device.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("device")

-- Source: ~/.config/hypr/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("input")
-- Source: ~/.config/hypr/gestures.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("gestures")

-- Source: ~/.config/hypr/rules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("rules")
