-- https://wiki.hyprland.org/Configuring/Variables/#input
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    input = {
        kb_layout = "us, gb",
        kb_variant = "",
        kb_model = "",
        kb_options = "ctrl:nocaps",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = true,
            disable_while_typing = true,
        },
    },
})

