-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    master = {
        new_status = "master",
    },
})

