-- See https://wiki.hyprland.org/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = output_top,
    mode = "1920x1080@165",
    position = "2885x0",
    scale = "1",
})

hl.monitor({
    output = output_left,
    mode = "1920x1080@74.97",
    position = "1920x1080",
    scale = "1",
})

hl.monitor({
    output = output_right,
    mode = "1920x1080@74.97",
    position = "3840x1080",
    scale = "1",
})

hl.monitor({
    output = output_laptop,
    mode = "1920x1080@165",
    position = "0x0",
    scale = "1",
})

