-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- ######## Window rules ########
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(com.baphled.btop)$",
    },
    opacity = "0.9 override",
})

hl.window_rule({
    match = {
        class = "^(brave-browser)$",
    },
    opacity = "1.0 override",
})

hl.window_rule({
    match = {
        class = "^(com.baphled.btop)$",
    },
    fullscreen = true,
})

hl.window_rule({
    match = {
        class = "^(blueberry.py)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(steam)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(guifetch)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(1Password)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(dev.warp.Warp)$",
    },
    float = false,
})

hl.window_rule({
    match = {
        title = "^(Open File)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "^(Select a File)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "^(Choose wallpaper)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "^(Open Folder)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "^(Rename)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "^(Save As)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "^(Library)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        title = "^(File Upload)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(1Password)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(Preferences)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(com.waybar.calcurse)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(com.waybar.alsamixer)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(com.waybar.garuda)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(com.waybar.pacseek)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(com.waybar.nmtui)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(com.nm-connection.editor)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(org.gnome.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(About)(.*)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(lxqt-policykit-agent)(.*)$",
    },
    center = true,
})

-- Picture-in-Picture
hl.window_rule({
    match = {
        title = "^(Picture(-| )in(-| )[Pp]icture)$",
    },
    keep_aspect_ratio = true,
    move = "73% 72%",
    size = "25% 25%",
    float = true,
    pin = true,
    opacity = "1.0 override",
})

-- Plex Media Player
hl.window_rule({
    match = {
        title = "^(tv.plex.Plex|Plex)$",
    },
    keep_aspect_ratio = true,
    move = "73% 72%",
    size = "45% 45%",
    float = true,
    pin = true,
    opacity = "1.0 override",
})

-- Dialogs
hl.window_rule({
    match = {
        title = "^(Rename)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Open File)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Select a File)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Choose wallpaper)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Open Folder)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Save As)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Library)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(File Upload)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(1password)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(dialog)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(xdg-desktop-portal-gtk)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(org.gnome.FileRoller)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(Preferences)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(com.waybar.calcurse)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(com.waybar.alsamixer)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(com.waybar.garuda)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(com.waybar.pacseek)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(com.waybar.nmtui)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(com.nm-connection.editor)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(lxqt-policykit-agent)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(File Operation Progress)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(About)(.*)$",
    },
    float = true,
})

-- Tearing
hl.window_rule({
    match = {
        class = "^(steam_app)(.*)$",
    },
    immediate = true,
})

-- No shadow for tiled windows
hl.window_rule({
    match = {
        float = 0,
    },
    no_shadow = true,
})

-- ######## Layer rules ########
hl.layer_rule({
    match = { namespace = ".*" },
    xray = true,
})

-- layerrule = animation none, match:namespace .*
hl.layer_rule({
    match = { namespace = "walker" },
    animation = "none",
})

hl.layer_rule({
    match = { namespace = "selection" },
    animation = "none",
})

hl.layer_rule({
    match = { namespace = "overview" },
    animation = "none",
})

hl.layer_rule({
    match = { namespace = "anyrun" },
    animation = "none",
})

hl.layer_rule({
    match = { namespace = "indicator.*" },
    animation = "none",
})

hl.layer_rule({
    match = { namespace = "osk" },
    animation = "none",
})

hl.layer_rule({
    match = { namespace = "hyprpicker" },
    animation = "none",
})

hl.layer_rule({
    match = { namespace = "shell:*" },
    blur = true,
    ignore_alpha = 0.6,
})

hl.layer_rule({
    match = { namespace = "noanim" },
    animation = "none",
})

hl.layer_rule({
    match = { namespace = "gtk-layer-shell" },
    blur = true,
    ignore_alpha = 0,
})

hl.layer_rule({
    match = { namespace = "launcher" },
    blur = true,
    ignore_alpha = 0.5,
})

hl.layer_rule({
    match = { namespace = "notifications" },
    blur = true,
    ignore_alpha = 0.69,
})

--####### Application rules ########
hl.window_rule({
    match = {
        class = "^(com.mitchellh.ghostty)$",
    },
    workspace = "1 silent",
})

hl.window_rule({
    match = {
        class = "^(com.baphled.neovim)$",
    },
    workspace = "1 silent",
})

hl.window_rule({
    match = {
        class = "^(md.Obsidian)$",
    },
    workspace = "2 silent",
})

hl.window_rule({
    match = {
        class = "^(com.baphled.notes)$",
    },
    workspace = "2 silent",
})

hl.window_rule({
    match = {
        class = "^(firefox)$",
    },
    workspace = "3 silent",
})

hl.window_rule({
    match = {
        class = "^(brave-browser)$",
    },
    workspace = "3 silent",
})

hl.window_rule({
    match = {
        class = "^(Chromium)$",
    },
    workspace = "3 silent",
})

hl.window_rule({
    match = {
        class = "^(firefox-esr)$",
    },
    workspace = "3 silent",
})

hl.window_rule({
    match = {
        class = "^(discord)$",
    },
    workspace = "4 silent",
})

hl.window_rule({
    match = {
        class = "^(Slack)$",
    },
    workspace = "4 silent",
})

hl.window_rule({
    match = {
        class = "^(com.baphled.email)$",
    },
    workspace = "6 silent",
})

hl.window_rule({
    match = {
        class = "^(com.baphled.newsboat)$",
    },
    workspace = "7 silent",
})

hl.window_rule({
    match = {
        class = "^(thunar)$",
    },
    workspace = "8 silent",
})

hl.window_rule({
    match = {
        class = "^(libreoffice-writer)$",
    },
    workspace = "8 silent",
})

hl.window_rule({
    match = {
        class = "^(com.baphled.remote)$",
    },
    workspace = "9 silent",
})

hl.window_rule({
    match = {
        class = "^(com.baphled.btop)$",
    },
    workspace = "10 silent",
})

hl.window_rule({
    match = {
        class = "^(md.Obsidian)$",
    },
    group = "set " .. workspace_notes,
})

